import {VERSION, syncVersions} from './version.mjs';
syncVersions();
import { copyFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { root, runMoon } from './moon.mjs';
runMoon(['build', '--target', 'js', '--release']);
mkdirSync(resolve(root, 'dist'), {recursive: true});
copyFileSync(resolve(root, '_build/js/release/build/bridge/bridge.js'), resolve(root, 'dist/core.mjs'));
copyFileSync(resolve(root, '_build/js/release/build/analytics_bridge/analytics_bridge.js'), resolve(root, 'dist/formal-analytics.mjs'));
console.log(`Built MoonMMDB ${VERSION} (MoonBit core, JavaScript target).`);
runMoon(['build', '--target', 'js', '--release'], resolve(root,'examples/log_analytics'));
copyFileSync(resolve(root,'examples/log_analytics/_build/js/release/build/local/moonmmdb_log_analytics/moonmmdb_log_analytics.js'), resolve(root,'dist/analytics.mjs'));
