"""Install a small, pinned official corpus and generate cross-target byte fixtures."""
import argparse
import hashlib
import io
import json
from pathlib import Path
import urllib.request
import zipfile

ROOT = Path(__file__).resolve().parent.parent
COMMIT = '7fcd868842970b2d0657af799807cbe722fb738d'
URL = f'https://codeload.github.com/maxmind/MaxMind-DB/zip/{COMMIT}'
SHA = '2aad1dc1c439b91e5cb455a9bf61d2984d1590a2db17a09886c1de0d9e6af15e'
NORMAL = [f'MaxMind-DB-test-ipv{v}-{w}.mmdb' for v in (4, 6) for w in (24, 28, 32)] + ['MaxMind-DB-test-decoder.mmdb', 'GeoIP2-City-Test.mmdb', 'GeoLite2-ASN-Test.mmdb']
NORMAL += [f'MaxMind-DB-test-mixed-{w}.mmdb' for w in (24,28,32)] + ['MaxMind-DB-test-metadata-pointers.mmdb','MaxMind-DB-no-ipv4-search-tree.mmdb','MaxMind-DB-string-value-entries.mmdb']
ADVERSARIAL = {
    'MaxMind-DB-test-pointer-decoder-dos.mmdb':'value-limit',
    'MaxMind-DB-test-pointer-decoder-dos-ipv6.mmdb':'value-limit',
    'MaxMind-DB-test-payload-amplification-dos.mmdb':'payload-limit',
    'MaxMind-DB-test-payload-amplification-dos-string.mmdb':'payload-limit',
    'MaxMind-DB-test-payload-amplification-dos-worst-case.mmdb':'payload-limit',
    'MaxMind-DB-test-metadata-payload-limit.mmdb':'payload-limit',
    'MaxMind-DB-test-decoder-payload-limit-over.mmdb':'payload-limit',
    'MaxMind-DB-test-decoder-value-limit-over.mmdb':'value-limit',
}
BOUNDARIES = {
    'libmaxminddb/libmaxminddb-deep-array-nesting.mmdb': ('1.1.1.1','depth-limit'),
    'libmaxminddb/libmaxminddb-deep-nesting.mmdb': ('1.1.1.1','depth-limit'),
    'libmaxminddb/libmaxminddb-metadata-marker-only.mmdb': ('1.1.1.1','out-of-bounds'),
    'libmaxminddb/libmaxminddb-offset-integer-overflow.mmdb': ('1.1.1.1','out-of-bounds'),
    'libmaxminddb/libmaxminddb-oversized-array.mmdb': ('1.1.1.1','value-limit'),
    'libmaxminddb/libmaxminddb-oversized-map.mmdb': ('1.1.1.1','value-limit'),
    'libmaxminddb/libmaxminddb-separator-record-max-left.mmdb': ('1.1.1.1','invalid-tree-pointer'),
    'libmaxminddb/libmaxminddb-separator-record-min-left.mmdb': ('1.1.1.1','invalid-tree-pointer'),
    'libmaxminddb/libmaxminddb-separator-record-min-right.mmdb': ('128.0.0.1','invalid-tree-pointer'),
    'libmaxminddb/libmaxminddb-uint64-max-epoch.mmdb': ('1.1.1.1',None),
    'maxminddb-golang/cyclic-data-structure.mmdb': ('1.1.1.1','out-of-bounds'),
    'maxminddb-golang/invalid-bytes-length.mmdb': ('1.1.1.1','out-of-bounds'),
    'maxminddb-golang/invalid-data-record-offset.mmdb': ('1.1.1.1','invalid-utf8'),
    'maxminddb-golang/invalid-map-key-length.mmdb': ('1.1.1.1','out-of-bounds'),
    'maxminddb-golang/invalid-string-length.mmdb': ('1.1.1.1','out-of-bounds'),
    'maxminddb-golang/metadata-is-an-uint128.mmdb': ('1.1.1.1','out-of-bounds'),
    'maxminddb-golang/unexpected-bytes.mmdb': ('1.1.1.1','out-of-bounds'),
    'maxminddb-python/bad-unicode-in-map-key.mmdb': ('1.1.1.1','invalid-separator'),
}

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--archive', type=Path)
    args = parser.parse_args()
    content = args.archive.read_bytes() if args.archive else urllib.request.urlopen(URL, timeout=45).read()
    if hashlib.sha256(content).hexdigest() != SHA:
        raise RuntimeError('Official archive SHA-256 mismatch')
    target = ROOT / 'tests' / 'fixtures'
    target.mkdir(parents=True, exist_ok=True)
    manifest = {'source': URL, 'commit': COMMIT, 'archive_sha256': SHA, 'license': 'Apache-2.0 OR MIT', 'files': []}
    generated = ['// Generated by scripts/prepare-fixtures.py from pinned MaxMind test data.', '// MaxMind, Inc. Apache-2.0 OR MIT; see tests/fixtures/LICENSE-*.', '']
    with zipfile.ZipFile(io.BytesIO(content)) as archive:
        names = {n.split('/', 1)[1]: n for n in archive.namelist() if not n.endswith('/')}
        for file in NORMAL:
            data = archive.read(names['test-data/' + file])
            (target / file).write_bytes(data)
            manifest['files'].append({'file': file, 'bytes': len(data), 'sha256': hashlib.sha256(data).hexdigest()})
            if file.startswith('MaxMind-DB-test-'):
                function = file.removesuffix('.mmdb').replace('MaxMind-DB-test-', 'fixture_').replace('-', '_')
                literal = ''.join(f'\\x{b:02x}' for b in data)
                generated += ['///|', f'fn {function}() -> Bytes {{ b"{literal}" }}', '']
        for file in ('LICENSE-APACHE', 'LICENSE-MIT'):
            (target / file).write_bytes(archive.read(names[file]))
        for file in ('GeoIP2-City-Test.json', 'GeoLite2-ASN-Test.json'):
            (target / file).write_bytes(archive.read(names['source-data/' + file]))
        adversarial = target / 'adversarial'
        adversarial.mkdir(exist_ok=True)
        bad_manifest = []
        for file, code in ADVERSARIAL.items():
            data = archive.read(names['test-data/' + file])
            (adversarial/file).write_bytes(data)
            bad_manifest.append({'file':file,'expected_code':code,'bytes':len(data),'sha256':hashlib.sha256(data).hexdigest()})
        (adversarial/'manifest.json').write_text(json.dumps(bad_manifest,indent=2)+'\n',encoding='utf-8')
        boundary = target / 'boundary'
        boundary.mkdir(exist_ok=True)
        boundary_manifest = []
        cases = [('bad-data/'+path, ip, code) for path,(ip,code) in BOUNDARIES.items()]
        cases += [('test-data/MaxMind-DB-test-decoder-'+suffix+'.mmdb','1.1.1.1',code) for suffix,code in [('payload-limit',None),('value-limit','value-limit'),('value-limit-pointer-heavy','value-limit')]]
        for source,ip,code in cases:
            file = source.split('/')[-1]
            data = archive.read(names[source])
            (boundary/file).write_bytes(data)
            boundary_manifest.append({'file':file,'source_path':source,'ip':ip,'expected_code':code,'bytes':len(data),'sha256':hashlib.sha256(data).hexdigest()})
        (boundary/'manifest.json').write_text(json.dumps(boundary_manifest,indent=2)+'\n',encoding='utf-8')
    (target / 'manifest.json').write_text(json.dumps(manifest, indent=2) + '\n', encoding='utf-8')
    (ROOT / 'src' / 'fixtures_wbtest.mbt').write_text('\n'.join(generated), encoding='utf-8')
    consumer = ROOT / 'examples/log_consumer'
    consumer.mkdir(parents=True,exist_ok=True)
    literal = ''.join(f'\\x{b:02x}' for b in (target/'GeoLite2-ASN-Test.mmdb').read_bytes())
    (consumer/'fixture.mbt').write_text('// Generated official MaxMind fixture; Apache-2.0 OR MIT.\n///|\nfn asn_fixture() -> Bytes { b"'+literal+'" }\n',encoding='utf-8')
    print(f'Prepared {len(NORMAL)} official fixtures with pinned hashes.')

if __name__ == '__main__':
    main()
