"""Test-only deterministic fixtures, not a public MMDB writer or real IP labels."""
import hashlib, json
from pathlib import Path
from importlib.util import spec_from_file_location, module_from_spec
ROOT=Path(__file__).resolve().parent.parent
spec=spec_from_file_location('scale', ROOT/'scripts/scale-verify.py')
enc=module_from_spec(spec);spec.loader.exec_module(enc)
OUT=ROOT/'tests/scenarios';OUT.mkdir(exist_ok=True)

def build(records,kind):
    # Two exact /24 prefixes in documentation-only address space.
    nodes=[{}]
    for prefix,record in records:
        node=0
        for depth in range(24):
            bit=(prefix>>(31-depth))&1
            if depth==23:nodes[node][bit]=('record',record)
            else:
                if bit not in nodes[node]:nodes[node][bit]=len(nodes);nodes.append({})
                node=nodes[node][bit]
    data=bytearray(); offsets={}; n=len(nodes)
    for _,record in records:
        offsets[record]=len(data)
        if kind=='geo':payload=enc.mapping([('country',enc.mapping([('iso_code',enc.text(record))]))])
        elif kind=='asn':payload=enc.mapping([('autonomous_system_number',enc.integer(6,int(record)))])
        else:payload=enc.mapping([('site',enc.text(record)),('purpose',enc.text('synthetic-demo'))])
        data.extend(payload)
    tree=bytearray()
    for node in nodes:
        for bit in (0,1):
            dest=node.get(bit,n)
            if isinstance(dest,tuple):dest=n+16+offsets[dest[1]]
            tree.extend(dest.to_bytes(3,'big'))
    meta=enc.mapping([('node_count',enc.integer(6,n)),('record_size',enc.integer(5,24)),('ip_version',enc.integer(5,4)),('database_type',enc.text('MoonMMDB-Synthetic-'+kind)),('binary_format_major_version',enc.integer(5,2)),('binary_format_minor_version',enc.integer(5,0)),('build_epoch',enc.integer(9,0)),('languages',enc.field(11,enc.text('en'),1)),('description',enc.mapping([('en',enc.text('Synthetic scenario; not geolocation data'))]))])
    return bytes(tree)+bytes(16)+data+b'\xab\xcd\xefMaxMind.com'+meta

files={}
for name,kind,values in [('geo','geo',['ZZ','YY']),('asn','asn',['64512','64513']),('tags','tags',['lab-a','lab-b']),('tags-updated','tags',['lab-a-new','lab-b'])]:
    data=build([(0xc0000200,values[0]),(0xc6336400,values[1])],kind)
    path=OUT/(name+'.mmdb');path.write_bytes(data)
    files[path.name]={'sha256':hashlib.sha256(data).hexdigest(),'bytes':len(data)}
(OUT/'manifest.json').write_text(json.dumps({'source':'Generated by scripts/prepare-scenarios.py; Apache-2.0 project code; artificial documentation-address labels, not real geolocation.', 'files':files},indent=2)+'\n',encoding='utf-8')
print('Prepared four synthetic scenario databases')
