import {readFileSync, writeFileSync, readdirSync} from 'node:fs';
import {resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
export const root = fileURLToPath(new URL('../', import.meta.url));
export function parseVersion(value) {
  if (!/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/.test(value)) throw new Error('Expected a stable major.minor.patch version');
  const parts = value.split('.').map(Number);
  if (!parts.every(Number.isSafeInteger)) throw new Error('Version component exceeds safe integer');
  return parts;
}
export function atLeast(value, minimum) {
  const a=parseVersion(value), b=parseVersion(minimum);
  for (let i=0;i<3;i++) if(a[i]!==b[i]) return a[i]>b[i];
  return true;
}
export const VERSION = readFileSync(resolve(root,'moon.mod'),'utf8').match(/^version = "([^"]+)"$/m)?.[1];
parseVersion(VERSION);
export function capabilities(version) {
  if(!atLeast(version,'0.3.0')) throw new Error('Registry verification requires version >= 0.3.0');
  return {enrichment:atLeast(version,'0.4.0'), geo:atLeast(version,'0.6.0'), analytics:atLeast(version,'0.9.0')};
}
export function assertAdvance(version, previous) {
  if(!atLeast(version,previous)||version===previous)throw new Error('Release version must advance without replacing history');
}
export function syncVersions(write=false) {
  const files=['package.json','web/package.json','web/package-lock.json','native_cli/moon.mod',
    ...readdirSync(resolve(root,'examples'),{withFileTypes:true}).filter(d=>d.isDirectory()).map(d=>`examples/${d.name}/moon.mod`),
    'src/model.mbt','native_cli/main.mbt','native_cli/analyze.mbt','web/src/version.ts','bin/version.mjs'];
  const stale=[];
  for(const file of files) {
    let old;try{old=readFileSync(resolve(root,file),'utf8');}catch{if(!['web/src/version.ts','bin/version.mjs'].includes(file))continue;old='';}
    let next=old;
    if(file==='web/src/version.ts'||file==='bin/version.mjs') next=`// Generated by scripts/version.mjs from moon.mod.\nexport const VERSION = '${VERSION}';\n`;
    else if(file.endsWith('.json')) {
      const obj=JSON.parse(old);obj.version=VERSION;
      if(obj.packages?.[''])obj.packages[''].version=VERSION;
      next=JSON.stringify(obj,null,2)+'\n';
    } else if(file.endsWith('moon.mod')) next=old.replace(/HhWw96\/moonmmdb@\d+\.\d+\.\d+/g,`HhWw96/moonmmdb@${VERSION}`).replace(/^(version = ")[^"]+("$)/m,`$1${VERSION}$2`).replace(/("HhWw96\/moonmmdb"\s*:\s*")[^"]+"/g,`$1${VERSION}"`);
    else next=old.replace(/0\.\d+\.\d+/g,VERSION);
    if(next.replaceAll('\r\n','\n')!==old.replaceAll('\r\n','\n')){stale.push(file);if(write)writeFileSync(resolve(root,file),next);}
  }
  if(stale.length&&!write)throw new Error('Stale version sources: '+stale.join(', '));
  return stale;
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)) {
  if(process.argv.includes('--sync'))console.log(syncVersions(true));
  else if(process.argv.includes('--check')){syncVersions();console.log('Version sources match '+VERSION);}
  else console.log(VERSION);
}
